apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis-database
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis