apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tejks/lm-auth
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_HOSTNAME
              value: mongodb-0.mongodb-headless.database
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: auth
            - name: MONGODB_USERNAME
              value: tejks
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: db-password
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats:4222'
            - name: NATS_CLUSTER_ID
              value: login-management
            - name: JWT_KEY
              value: jwtkey